### ISSUE TITLE
Please clarify what selector is being used in the documentation

### ISSUE THREAD

**Issue by benlieb** [Hirurg103/capybara_select2#15]
I spent about an hour trying to figure out what selector (#my_selector) was being used. I tried the id of the select tag in question, then looked for options to pass an explicit id to select2, then spend time reading through your source code. 

It was only after reading your own specs, and [your HTML files](https://github.com/Hirurg103/capybara_select2/blob/master/spec/fixtures/select2-v4/index.html) that I discovered how to use your code. I appreciate your work, and that you've made it available, but it is extremely frustrating to have to do this.

It was not clear until then that #my_selector is an unrelated unique parent of the select2 element being targeted...

**Comment by Hirurg103** [comment]
Hi Benjamin,

Ok, will do

**Comment by Hirurg103** [comment]
Hi @benlieb 

actually there are [examples how to use the helper](https://github.com/Hirurg103/capybara_select2#select-from-a-node-containing-select2-control) with CSS and xPath selector.

CSS and xPath selectors should identify a block which wraps select2 element or select2 element itself (the html element with the `.select2-container` class). Do you want to see it in the README?

**Comment by benlieb** [comment]
Yes I think this

> CSS and xPath selectors should identify a block which wraps select2 element or select2 element itself (the html element with the .select2-container class)


would be VERY helpful in the README

**Comment by benlieb** [comment]
Yes I think this

> CSS and xPath selectors should identify a block which wraps select2 element or select2 element itself (the html element with the .select2-container class)
> 

would be VERY helpful in the README

**Comment by mlt** [comment]
I wonder if we could add a fallback or another option to use id/css referring to plain old select that is being turned into select2? I mean I do not have an associated label and/or id for select2. I do have an id for plain old select though. So currently I use `select2 "whatever", css: '#something + span.select2'`. Maybe just mention that in readme as well?

**Comment by Hirurg103** [comment]
Hi @mlt, I'm sorry for the late reply.

> I wonder if we could add a fallback or another option to use id/css referring to plain old select that is being turned into select2?

No. There are two reasons for it:
1. A select2 widget has nothing to do with the plain old select it was created from. A select2 element can be created based on data from an array or a remote data source (see [select2 data sources](https://select2.org/data-sources)).
2. Select2 hides plain old select. It is not a good practice to manipulate hidden elements with Capybara because users cannot see them.

> I do not have an associated label and/or id for select2. I do have an id for plain old select though. So currently I use `select2 "whatever", css: '#something + span.select2'`. Maybe just mention that in readme as well?

I think that `select2 'whatever', css: '#something .select2'` will be fine.

Also you can use the following code snippet to find a select2 element using the ID of the plain old select from which it was created:

```ruby
select2 'whatever', xpath: find('#plain-select-id', visible: false).sibling('.select2').path
```

but it looks more cumbersome to me.

**Comment by mlt** [comment]
👋 I do not propose to manipulate original select, but just to add a syntax sugar to locate select2 made out of it (usually ❔ a sibling element) in a less verbose way.

> … OR an HTML element containing a select2 element

That is the thing... just an extra line for those impatient who convert plain old selects into select2 that become siblings. I think `+` is important. There is no parent I can easily reference. However I'm not sure if that relies on current implementation detail of select2 and may brake in the future... 🤷 And yes, xpath is an overkill here.
![image](https://user-images.githubusercontent.com/413384/103104463-fb8f4100-45ec-11eb-9068-43438b7a5dbc.png)

**Comment by wmulligan87** [comment]
+1 to this issue.

I have some forms that don't have matching labels for each input
![image](https://user-images.githubusercontent.com/1403611/114807151-4aa1f180-9de9-11eb-8b29-272e401b3d01.png)

![image](https://user-images.githubusercontent.com/1403611/114807385-a9676b00-9de9-11eb-96e1-ef5276f12dd0.png)

The UI shows a placeholder 'Organisations' in this scenario, and we've previously used that data-placeholder attribute to find the select2 element (before finding this helpful library!). The issue is due to the behaviour noted above. Currently my workaround looks like:
```
select2('Organisation 1', xpath: find("[data-placeholder='Organisations']", visible: false).sibling('.select2').path)
```

It'd be preferrable if the css/xpath options could be tested on the original element, resulting in something like:
```
select2('Organisation 1', css: '[data-placeholder=Organisations]')
```

or better yet, considering data-placeholder core functionality for the select2 library (https://select2.org/configuration/data-attributes), maybe a placeholder option
```
select2('Organisation 1', placeholder: 'Organisations')
```

**Comment by Hirurg103** [comment]
@wmulligan87, there is a note in the README that

> CSS and XPath selectors must identify an HTML node that wraps select2 element or a select2 element itself (an HTML element with the `.select2-container` class)

With that in mind you can select 'Organisation 1' with

```ruby
select2('Organisation 1', css: '[data-select2-id="10"]')
```

I think it makes sense to move the note to the top of the [Examples](https://github.com/Hirurg103/capybara_select2#examples) section and add an example of how to use the `select2` helper with a parent of a select2 element.

> or better yet, considering `data-placeholder` is core functionality for the select2 library (https://select2.org/configuration/data-attributes), maybe a placeholder argument
> 
> ```
> select2('Organisation 1', placeholder: 'Organisations')
> ```

I like the idea with the placeholder option. If you wish, you can implement this feature and open a PR with it.
